### ISSUE TITLE
touch button use on WidgetSwitcher 

### ISSUE THREAD

**Issue by MatrixHan** [AimoTvT/UITouch#1]
touch button use on WidgetSwitcher ,  TouchButton is layer hide , but receive pressed event, throw  TArray out of bound.

**Comment by AimoTvT** [comment]
可以设置禁用模式,需要使用控件时解除禁用 TouchWidget.h(bool bDisabled = false),后续可能添加为函数来设置

**Comment by AimoTvT** [comment]
可以设置禁用模式，需要使用控件时解除禁用 TouchWidget.h（void SetDisabled(bool bIsDisabled)）
