### ISSUE TITLE
Error on compile time (Installed plugin from git)

### ISSUE THREAD

**Issue by Syndi-Online** [AimoTvT/UITouch#3]
![image](https://github.com/AimoTvT/UITouch/assets/145366805/29eb2938-a680-4dfa-ac41-4edc5d243822)

Commit: [41dd398](https://github.com/AimoTvT/UITouch/commit/41dd3982e6ed2a9eb57ff9747fd3b3e647c3f761)
Build Platform : Linux (Ubuntu in CT) 
UE Version: 5.3.2 (From source)

Error on compile time (Installed plugin from git)  , Other plugins are built without problems
You just need to place () in the condition
Win and Mac (OSX) build correct

**Comment by AimoTvT** [comment]
请问一下,Linux,应该如何修复改段代码,
if ((TouchIndexs[i] && bIsCurrentlyPressed == false) || IsClamp(Vector, Vector2) == false)
修改为这样有用吗?

**Comment by AimoTvT** [comment]
请问一下，Linux，应该如何修复改段代码，
if （（TouchIndexs[i] && bIsCurrentPressed == false） || IsClamp（Vector， Vector2） == false）
修改为这样有用吗？

**Comment by AimoTvT** [comment]
已修复!

**Comment by AimoTvT** [comment]
> ![image](https://private-user-images.githubusercontent.com/145366805/310299876-29eb2938-a680-4dfa-ac41-4edc5d243822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2ODAyODcsIm5iZiI6MTcwOTY3OTk4NywicGF0aCI6Ii8xNDUzNjY4MDUvMzEwMjk5ODc2LTI5ZWIyOTM4LWE2ODAtNGRmYS1hYzQxLTRlZGM1ZDI0MzgyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMzA2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzU1N2VkN2Q0YzM1MTc3MDMxOGUzMTQ3YzA3ZDA5ZWQxZTgzODYxNGIzZDM4MjI4NjQyOWM2YjJkZjA5MTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z4sJEivTva9WrhZ-MseOfK6mrlGoWirlPriWWrBgNb0)
> 
> Commit: [41dd398](https://github.com/AimoTvT/UITouch/commit/41dd3982e6ed2a9eb57ff9747fd3b3e647c3f761) Build Platform : Linux (Ubuntu in CT) UE Version: 5.3.2 (From source)
> 
> Error on compile time (Installed plugin from git) , Other plugins are built without problems You just need to place () in the condition Win and Mac (OSX) build correct

感谢提供错误描述
