### ISSUE TITLE
Error on compile time 

### ISSUE THREAD

**Issue by Syndi-Online** [AimoTvT/UITouch#4]
![image](https://github.com/AimoTvT/UITouch/assets/23487556/e2c87deb-77fa-40d4-9c09-e04f7c4fb1e2) 
Build Platform : Linux (Ubuntu in CT)
UE Version: 5.3.2 (From source)

Error on compile time (Installed plugin from git), Other plugins are built without problems
You just add a default value 
bool bIsCurrentlyPressed = false;
Win and Mac (OSX) build correct

**Comment by AimoTvT** [comment]
已修复
